### ISSUE TITLE
isOpen is interpreted as !isOpen (opposite)

### ISSUE THREAD

**Issue by LA** [negomi/react-burger-menu#204] opened 2017-10-27 21:50 UTC
I was kind of confused as to why my menu was opening by default, but after some investigation, I figured out isOpen is being interpreted as !isOpen somewhere. 

Maybe I misread the docs, but I was led to believe that passing `<Menu isOpen={false} />` would mean the menu would not open by default. Then when I pass `isOpen={true}` it renders not open.

It is working though, as of now, by just passing `!this.state.isMenuOpen`.

**Comment by negomi** [comment] 2017-10-28 20:57
Hey @LA,

I might need a little more information to figure out what's going on.

It sounds like you're describing the correct behavior:
```js
<Menu isOpen={false} /> // Renders closed
<Menu isOpen={true) /> // Renders open
```

Are you saying you passed `isOpen={true}` and the menu rendered closed?

If you can paste a bit more of your code (menu and its parent component), I can dig into it a bit more.

**Comment by LA** [comment] 2017-11-03 18:21
@negomi That's exactly what I'm saying.

`<Menu isOpen={true} styles={menuStyles}>`
is rendered with the menu closed which is my desired behavior.

`<Menu isOpen={false} styles={menuStyles}>`
is rendered with the menu open.

I am not sure what else I need to present.

```
<Menu isOpen={true} styles={menuStyles}>
  <Link className='menu-item' to={'/'}>
    <p>
      Download
    </p>
  </Link>
</Menu>
// renders with menu closed
```

**Comment by negomi** [comment] 2017-11-08 04:50
@LA I wasn't able to reproduce this behavior with the component in isolation, which is why I suspected there may be something else going on with your setup.

However, looking back over the burger menu code, I did discover a small bug where the use of `isOpen` was toggling the menu open and closed one time too many, which might also have been a contributing factor.

Would you mind upgrading to the latest version to see if the fix for that solves your problem?

If not, it would be super helpful if you could push up a small repo demonstrating the issue so I have somewhere to start debugging.

Thanks!

**Comment by MaralS** [comment] 2017-12-27 09:49
@negomi : do you have a solution for this issue ? 
I tried to uninstall and install again react-burger-menu with yarn but it did not work.

**Comment by LA** [comment] 2017-12-27 18:13
@negomi @MaralS  Sorry I'm not being helpful, but I've had 0 problems just running !isOpen, so that's what I'm going to continue to do. If I do find some time I'll try to make a new repo.

**Comment by MaralS** [comment] 2017-12-28 10:49
@LA @negomi I had to keep the param to true in order to have the menu closed at the rendering.
It's really frustrating. It maybe due to of Gatsby … I'm using this to build my project 
Anyone have a problem using React menu burger with Gatsby ?

**Comment by MaralS** [comment] 2018-01-02 11:07
@negomi You can clone my project  - https://github.com/MaralS/autocontrole

Thank you in advance !

**Comment by negomi** [comment] 2018-01-02 17:40
@MaralS thank you! I'll take a look at this later today :)

**Comment by negomi** [comment] 2018-01-03 07:31
Hi @MaralS, the issue in your case is layout and styling rather than `isOpen`. Things to be aware of:

1. You have two instances of `Menu` (one in assets/components/header.js and one in assets/components/navigation.js). The one in header.js isn't actually being used anywhere, but you're not passing any styles/props to the other one.
2. Don't set `menuWrap` to 100% width - not sure what you're trying to do here but that style isn't needed in most cases. Use the `width` prop instead.
3. You need to put `Navigation` at the beginning of your header element in layouts/index.js, like this:
```
<header>
    <Navigation />
    <div className="site-title">
        <Link to='/' title="Auto contr&ocirc;le des Hexagones">
        Auto contr&ocirc;le des Hexagones</Link>
    </div>
</header>
```
4. If you want the menu aligned with the top of the screen, move it to the top of your nav component, above the `<ul className="main-menu">`.
5. I noticed you positioned your burger icon to the right. If you want it to open from the right, just pass the `right` prop.

If I make these changes, the menu works as expected.

**Comment by MaralS** [comment] 2018-01-03 08:55
@negomi thanks for the explanation :) 
However in the meantime I deleted the navigation.js file, I defined all menu components in header.js.

I pushed my recents modifications on the repo. It still not works :/

**Comment by negomi** [comment] 2018-01-03 19:18
@MaralS no problem :)

Now the issue is that the menu does not work well as a flex item.

If you add these styles to your `.mobile` class, the overlay is visible:

```
position: fixed;
width: 100%;
```

**Comment by MaralS** [comment] 2018-01-04 09:18
@negomi thank you so much :)

**Comment by negomi** [comment] 2018-01-06 21:02
I'm going to close this for now as I'm still not able to reproduce broken behavior with `isOpen`, but feel free to post a link to a repo if you get time, and I will reopen it.

@LA

**Closed by negomi** 2018-01-06 21:02 UTC
