### ISSUE TITLE
onStateChange callback not firing

### ISSUE THREAD

**Issue by Sorgrum** [negomi/react-burger-menu#209] opened 2017-11-29 20:42 UTC
```js
<MobileNav isOpen={this.state.navopen} styles={styles} onStateChange={ isMenuOpen }>
  {this.props.children}
</MobileNav>
```
I'm trying to use onStateChange to keep my `this.state.navopen` updated. I've tried the following:
```js
var isMenuOpen = function(state) {
  console.log(state);
  return state.isOpen;
}
```
```js
updateMobileNavState = (state) => {
  console.log(state);
};
```
None of them seem to work. It doesn't look to me like the callback is happening at all because my console is showing nothing in it.

**Comment by negomi** [comment] 2017-12-28 19:58
Hi @Sorgrum, sorry for the late response. Did you get this working?

If not, have you tried passing an anonymous function directly to `onStateChange` (`onStateChange={(state) => console.log(state)}`)?

If that doesn't work, check you're importing the menu correctly (I would expect that to look like `import { slide as MobileNav } from 'react-burger-menu'` in your case).

If that still doesn't work, if you can send me a link to your code reproducing the problem, I can take a look for you.

**Comment by Sorgrum** [comment] 2017-12-29 13:52
It's working perfectly now, without any real change on my end. Odd but maybe some issue with my environment. Thanks!

**Comment by mwq27** [comment] 2018-04-21 21:00
I apologize for opening this up again, but I'm having this same problem and can't figure it out.  Using version 2.4.2.  Here's some code:
```js
// alerts.ts
// initializing the menu 
import { slide as AlertsMenu } from 'react-burger-menu';
import { decorator as reduxBurgerMenu } from 'redux-burger-menu';

export default reduxBurgerMenu(AlertsMenu, 'alerts');
```
```jsx
// app-container.tsx
// Using the menu
<AlertsMenu
          right={true}
          styles={styles}
          pageWrapId={'page-wrap'}
          outerContainerId={'outer-container'}
          isOpen={this.props.isAlertsOpen}
          onStateChange={(state) => console.log(state)}
          customBurgerIcon={false}
        > ...
```

```js
// navbar.tsx
// opening the menu with a redux action
import { action as toggleMenu } from 'redux-burger-menu';
...
openAlerts = () => {
    this.props.actions.toggleMenu(!this.props.isOpen, 'alerts');
  };

```
The `onStateChange` just never fires.  Anything that I might be missing?  Thanks

**Comment by mwq27** [comment] 2018-04-21 21:45
So digging a bit more into the code, it looks like the `onStateChange` method that is provided by redux-burger-menu decorator overrides whatever `onStateChange` method you pass into the component. Is this what's supposed to happen?

Thanks

**Comment by negomi** [comment] 2018-04-21 22:35
Hey @mwq27, ah yes you're right.

This was based on an assumption that the main/only use for `onStateChange` would be controlling the open state of the menu, but this is absolutely not necessarily the case.

I'm happy to fix this - thanks for reporting it!

**Comment by negomi** [comment] 2018-04-22 00:09
This is now fixed - you'll need to update redux-burger-menu to v0.2.5.

**Closed by negomi** 2018-04-22 00:09 UTC
Labels: bug

**Comment by mwq27** [comment] 2018-04-23 15:07
Great, thank you @negomi
