### ISSUE TITLE
Unknown prop `_radiumDidResolveStyles` on <div>

### ISSUE THREAD

**Issue by hansbonini** [negomi/react-burger-menu#75] opened 2016-07-02 21:57 UTC
Im getting this error in console and menu don`t show up.
How to solve?

Warning: Unknown prop `_radiumDidResolveStyles` on <div> tag. Remove this prop from the element. For details,

**Comment by negomi** [comment] 2016-07-03 02:10
This is caused by updating to React 15.2.0, which introduces warnings about unknown props.

The actual error is being thrown by Radium, which this package depends on. Looks like they already have an issue open about this: https://github.com/FormidableLabs/radium/issues/759

So you can keep an eye on that for updates, or downgrade to React 15.1 to avoid the error for now if it's an issue.

**Comment by snakeyak** [comment] 2016-07-15 22:06
should be fixed in radium v0.18.0, update package pls?

**Comment by negomi** [comment] 2016-07-16 18:14
This is now fixed. The current semver range will allow for minor version updates of dependencies, so no need for an update in this package. Thanks!

**Closed by negomi** 2016-07-16 18:14 UTC

**Comment by snakeyak** [comment] 2016-07-16 18:17
Ah ok, thank you Imogen!

**Comment by Vincz** [comment] 2016-07-18 12:45
Hi :)

Looks like the warning have been fixed in Radium v0.18 (see https://github.com/FormidableLabs/radium/commit/bf2ce19d4c5ccad0a8487c535338877b241e0104).
When installing react-burger-menu, it keeps installing radium v0.17.2.

**Comment by SpainTrain** [comment] 2016-07-18 22:58
`"radium": "^0.17.0",` that semver range does not pick up `0.18.X` 

> ^0.2.3 := >=0.2.3 <0.3.0

https://github.com/npm/node-semver#caret-ranges-123-025-004

Fixed here: https://github.com/negomi/react-burger-menu/pull/82

check out https://www.npmjs.com/package/npm-check which is an awesome tool to help with updating deps (no need to memorize node-semver rules)

**Comment by negomi** [comment] 2016-07-19 03:40
This is fixed in v1.9.9.

Thanks for the link to the more thorough explanation @SpainTrain. I did not know about the left-most non-zero digit rule when using caret ranges. I'd read https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-publishers, and other things which unfortunately all failed to specifically mention this detail.

Yay for learning new things at least 😄
