### ISSUE TITLE
Push menu closed always shows page-wrapper as opened and vice versa

### ISSUE THREAD

**Issue by matejstrasek** [negomi/react-burger-menu#53] opened 2016-04-07 14:54 UTC
I am experiencing this weird error with the 'push' menu. 'isOpen' is set based on the state of the menu. When the app is loaded its set to false. The BurgerMenu is hidden, but page-wrapper is shifted to the right as it would be opened.

```
<BurgerMenu
  width={290}
  pageWrapId={'page-wrapper'}
  outerContainerId={'outer-container'}
  styles={styles}
  onStateChange={this.stateChange.bind(this)}
  isOpen={isOpen}>
    <Menu {...menuProps}/>
</BurgerMenu>
```

It looks like the isOpen is somehow failing - setting it to false closes the menu, but opens the wrapper and vice versa; setting it to true opens the menu and closes the wrapper.

**Comment by negomi** [comment] 2016-04-09 01:39
Hi @matejstrasek, sorry for the late response. I just merged a fix that I think addresses the same issue. If that doesn't work, let me know and I'll look into it as soon as I can.

**Comment by toddsmart** [comment] 2016-05-03 12:36
Hi. I think I'm running into something similar with 1.8.1. I'm using the 'push' react-burger-menu animation as follows:

container:
```
  render() {
    const burgerMenu = (
        <HamburgerMenu
          isOpen={this.props.visibilityFilter.isNavOpen}
          toggleNavigation={this.props.toggleNavigation}
        />
    );
    return (
      <div id="outer-container">
        {burgerMenu}
        <div id="page-wrap">
          {this.props.children}
        </div>
      </div>
    );
  }
```

the HamburgerMenu component that wraps the react-burger-menu (aka Menu):
```
<Menu isOpen={this.props.isOpen}
  onStateChange={(state) => this.handleStateChange(state)} 
  pageWrapId="page-wrap" 
  outerContainerId="outer-container">
```

the handleState Change within my HamburgerMenu:
```
handleStateChange(state) {
  if (this.props.isOpen !== state.isOpen) {
    this.props.toggleNavigation();
  }
  return state.isOpen;
}
```

When handling my own close events (i.e. when I click an item in the react-burger-menu, I toggle my apps' isOpen to false), things work fine.

However, when handling a close event from the react-burger-menu (i.e. hitting <esc> or clicking outside the menu), the react-burger-menu closes and then re-opens partially. In that, I mean the page-wrap area is displayed shifted to the right as if the menu is open, yet the menu is actually shown hidden.

From what I can tell, the synchronization call to handleStateChange that happens when the react-burger-menu is closed via <esc> or clicking outside the menu target area works fine. My app's isOpen state is false and the react-burger-menu state is false.

However, there is an additional call to handleStateChange after my apps HamburgerMenu component is rendered with isOpen=false. This call results in an additional call to the react-burger-menu's toggle that appears to be leaving the app and component in this state.

Any insight would be appreciated. In the meantime, I've shifted to using the 'slide' animation, which doesn't have to deal with these complexities.

**Comment by negomi** [comment] 2016-05-05 15:24
Thanks for letting me know - I'll try to reproduce this and look into it in the next couple of days.

**Comment by negomi** [comment] 2016-05-20 03:03
So, the logic in v1.8.1 that determined when the wrapper elements should be triggered was incorrect, resulting in that additional function call.

v1.8.3 should fix this issue, and includes more thorough testing covering this case, and several other bugs that have been caused by that same bit of logic.

Thanks for reporting the error!

**Closed by negomi** 2016-05-20 03:03 UTC
